---
title: "Untitled"
author: "Sean Park"
date: '2022 2 15 '
output: word_document
---
```{r}
retail = read.csv("total_data.csv", header = TRUE)
names(retail) = c("Date","Temp","Rain","Wind","Humd","Snow","G_temp", "A_temp","Date1","Day","Total_retail","Store_retail","Deliv_retail")
retail = subset(retail,select = -Date1)
summary(retail)
```


```{r}
retail["Odds"] = (retail$Store_retail/retail$Total_retail)/(1-(retail$Store_retail/retail$Total_retail))
summary(retail$Odds)
```

```{r}
retail["Deliv_per"] = retail$Deliv_retail/retail$Total_retail
summary(retail$Deliv_per)
```

```{r}
deliv_per.glm = glm(Deliv_per~Temp+Rain+Wind+Humd+Snow+G_temp+A_temp+Day, data=retail, family = binomial(link = "logit"))
summary(deliv_per.glm)
```
```{r}
step(deliv_per.glm, test="LRT")
```
```{r}
deliv_per.glm.A = glm(Deliv_per ~ Temp + G_temp, family = binomial(link = "logit"), 
    data = retail)
summary(deliv_per.glm.A)
```
```{r}
retail["isRain"] = retail["Rain"] != 0
retail["isSnow"] = retail["Snow"] != 0
deliv_per.glm.B = glm(Deliv_per~Temp+isRain+Wind+Humd+isSnow+G_temp+A_temp+Day, data=retail, family = binomial(link = "logit"))
summary(deliv_per.glm.B)
```
```{r}
plot(retail$Deliv_per)
plot(retail$Total_retail)
retail["Index"] = seq(1,length(retail))
```

```{r}
ind.lm = glm(Deliv_per ~ Index, data = retail,family = binomial(link="logit"))
summary(ind.lm)
```

